version: '3.8'
services:
  iptv-api:
    image: guovern/iptv-api:latest
    ports:
      - "8000:8000"
    volumes:
      - ./config:/iptv-api/config
      - ./output:/iptv-api/output
    restart: unless-stopped
